### ISSUE TITLE
Build is broken with pip 20.1

### ISSUE THREAD

**Issue by rbusquet** [stphivos/django-mock-queries#111]
```
Collecting django-mock-queries
  Downloading django_mock_queries-2.1.4.tar.gz (19 kB)
    ERROR: Command errored out with exit status 1:
     command: ~/.pyenv/versions/3.5.9/envs/venv/bin/python3.5 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/zx/2wg3gb553mzf9qmv349dbczr0000gp/T/pip-install-a_7srd3z/django-mock-queries/setup.py'"'"'; __file__='"'"'/private/var/folders/zx/2wg3gb553mzf9qmv349dbczr0000gp/T/pip-install-a_7srd3z/django-mock-queries/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/zx/2wg3gb553mzf9qmv349dbczr0000gp/T/pip-pip-egg-info-wafekgr9
         cwd: /private/var/folders/zx/2wg3gb553mzf9qmv349dbczr0000gp/T/pip-install-a_7srd3z/django-mock-queries/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/zx/2wg3gb553mzf9qmv349dbczr0000gp/T/pip-install-a_7srd3z/django-mock-queries/setup.py", line 9, in <module>
        req = [str(ir.req) for ir in install_req]
      File "/private/var/folders/zx/2wg3gb553mzf9qmv349dbczr0000gp/T/pip-install-a_7srd3z/django-mock-queries/setup.py", line 9, in <listcomp>
        req = [str(ir.req) for ir in install_req]
    AttributeError: 'ParsedRequirement' object has no attribute 'req'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

from https://github.com/pypa/pip/issues/2286#issuecomment-68285791

> @dstufft: A setup.py which is importing pip is a broken setup.py already. We do not offer a programmatic API for people to use nor do we offer any backwards compatibility guarantees for any of the functions inside of pip.

**Comment by rbusquet** [comment]
Pinned comment on pip's repo has a detailed explanation on why using pip in setup.py can cause issues: https://github.com/pypa/pip/issues/5599

**Comment by jonesnc** [comment]
I'm also getting this error when using pip 20.1

**Comment by stphivos** [comment]
Thanks! Merged fix and released [v2.1.5](https://pypi.org/project/django-mock-queries/) to PyPI.

**Comment by jonesnc** [comment]
Thanks for fixing this so quickly @stphivos!

**Comment by bmrobin** [comment]
encountered this and happy to find it not only already reported here, but fixed too! thanks
